### PR TITLE
getLists function

### PR DESCRIPTION
**Pull request by andreladocruz**
Added the function to get all Lists in the Mailchimp account

### CODE REVIEW

**Comment by nztim** [comment]
Hi Andre! Thanks for working on this. A couple of comments:

1. Have you tested this as-is? Line 25 references '$this->callApi()' but I think you meant 'api()'. Also the endpoint needs a leading slash.

2. The way things are structured for the other methods is that `MailchimpApi` has the actual API calls, `Mailchimp` uses them and does whatever it needs to do with the results. So, I'd suggest adding a new method to `MailchimpApi` in the 'API calls' section called `getLists()`, which has just the `$this->call()` reference. Then your `Mailchimp::getLists()` can call `MailchimpApi::getLists()` and handle the results. 

3. Could you please add a simple PHPUnit test for the method?

**Comment by andreladocruz** [comment]
Hi!!

Thanks for the reply and this full explanation. :) 
I learned some new stuff with you. Thanks.
This where the Way I solved my needs here and thought it will be useful for others user.
About the PHPUnit test, I did not got to this lesson yet. So, I'm afraid to do a even bigger mess with your code.
So, I'll be glad to see how you are going to deal with this change and learn form it. ;) 
Sorry for not helping you as you need. I really don't know how to create a PHPUnit teste for it. :(

**Comment by andreladocruz** [comment]
I forgot to answer you first question. :) 

Yes, I tested it as it is. I'm using it in a project I'm developing. ;) 

And it were working okay without the "/" in the end.

I used the $this->callApi() following the same logic in this method, for exemple:

`public function getListFields($list)
    {
        // https://us15.api.mailchimp.com/3.0/lists/ced785c83b/merge-fields
        $endpoint = "lists/{$list}/merge-fields";
        $response = $this->callApi('get', $endpoint);
        if (!empty($response['status']) && $response['status'] == 404) {
            return false;
        }
        return collect($response['merge_fields']);
    }`

**Comment by nztim** [comment]
I've updated the package to include this feature and below is an explanation of how I did it. I wrote it differently is so that the code remains consistent with itself - not because it's inherently better or correct.

Added `MailchimpApi::getLists()` - this is where the other API call methods are, and we don't need to duplicate the handling of 4XX errors because the code is already there. So it ends up being just one line.

Added `Mailchimp::getLists()` - this is the method provided to users of the package. It makes the API call, then discards the outer array and handles the empty case.

Added a simple test just to make sure it's not broken in future.

An improvement would be to add a `MailchimpList` class which wraps all the attributes returned by the API. The `Mailchimp::getLists()` method could then return an array of `MailchimpList` objects which would be easier to use than an array.

I hope this is useful and thanks for helping.

**Comment by andreladocruz** [comment]
Thanks for the explanation. :) And thanks for the upgrade!!!!

**Pull request closed without merging**
