### PR TITLE
Sets the number of rows to return from the API

### PR DESCRIPTION
**Pull request by andreladocruz**

### CODE REVIEW

**Comment by nztim** [comment]
Thanks for your submission. If we have parameters for getLists() then is there a reason to specifically offer count and not any parameter? I.e. why not getLists(array $parameters = [])? It could be that count is the most commonly used, but some of the others seem pretty useful too.

**Comment by andreladocruz** [comment]
@nztim , I totally agree with you. I was just in a hurry to enable this feature and now I´m on a business trip.

If anybody else could develop with this approach I'll be thankful. =)

**Comment by nztim** [comment]
I'll see what I can do :)

**Comment by andreladocruz** [comment]
@nztim , thanks!!! =)

**Comment by nztim** [comment]
I've pushed a new version as discussed, enjoy :)

**Pull request closed without merging**
